name: Build Laire Spinwheel

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter create --platforms=android .
      
      # JURUS PAMUNGKAS ANDROID: Paksa SDK ke versi 34
      - name: Force Android SDK
        run: |
          echo "flutter.compileSdkVersion=34" >> android/local.properties
          echo "flutter.minSdkVersion=23" >> android/local.properties
          
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LaireSpinwheel-Android
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter create --platforms=windows .
      
      # JURUS PAMUNGKAS WINDOWS: Suntik paksa pengabaian error ke file CMake
      - name: Force Silence C++ Warnings
        run: Add-Content -Path windows\CMakeLists.txt -Value "add_compile_definitions(_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS)"
        
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: LaireSpinwheel-Windows
          path: build\windows\runner\Release\*

  build-macos:
    name: Build macOS App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-macos-desktop
      - run: flutter create --platforms=macos .
      - run: flutter pub get
      - run: flutter build macos --release
      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: LaireSpinwheel-macOS
          path: build/macos/Build/Products/Release/*.app
